# Generated by Django 4.2.6 on 2025-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='new_title',
            field=models.CharField(default='Temporary title', max_length=255),
        ),
    ]
