# Generated by Django 4.2.6 on 2025-03-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blog_new_title_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(default='Ordinary', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
