# Generated by Django 4.2.6 on 2025-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blog_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
