# Generated by Django 4.2.6 on 2025-05-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdata',
            options={'verbose_name_plural': 'TaskDatas'},
        ),
        migrations.RenameField(
            model_name='taskdata',
            old_name='instructions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='file',
        ),
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='TaskFiles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taskdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.taskdata')),
            ],
            options={
                'verbose_name_plural': 'TaskFiles',
            },
        ),
    ]
