# Generated by Django 4.2.6 on 2025-05-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_taskdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Excel', 'Excel'), ('SPSS', 'SPSS'), ('Python', 'Python'), ('Machine Learning', 'Machine Learning'), ('Matlab', 'Matlab'), ('R', 'R'), ('Tableau', 'Tableau')], default='Excel', max_length=200),
        ),
    ]
