# Generated by Django 4.2.6 on 2025-05-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, null=True),
        ),
    ]
