# Generated by Django 4.2.6 on 2025-06-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='adminRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
