# Generated by Django 4.2.6 on 2025-06-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_task_completion_date_taskdata_adminread_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.task')),
            ],
            options={
                'verbose_name_plural': 'TaskNotifications',
            },
        ),
        migrations.CreateModel(
            name='AdminNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.task')),
            ],
            options={
                'verbose_name_plural': 'AdminNotifications',
            },
        ),
    ]
