# Generated by Django 4.2.6 on 2025-06-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_adminmessagenotifications_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
