# Generated by Django 4.2.6 on 2025-06-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_task_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
