# Generated by Django 4.2.6 on 2025-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_taskdata_is_auto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
    ]
