# Generated by Django 4.2.6 on 2025-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_taskdata_is_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='progress',
            field=models.IntegerField(blank=True, choices=[(30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90')], null=True),
        ),
    ]
